version: 2.1

orbs:
  python: circleci/python@1.2
  coveralls: coveralls/coveralls@1.1.0  # Use the latest version

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    parallelism: 4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: |
            pip install pytest pytest-mpl coveralls coverage pytest-cov \
                        mkdocs-awesome-pages-plugin pheasant mkdocstrings mkdocs-material
      - run:
          name: Install netplotbrain
          command: pip install ./
      - run:
          name: Run tests with coverage
          command: |
            pytest $(circleci tests glob "tests/**/*.py" | circleci tests split --split-by=timings) \
                   --cov=netplotbrain --cov-config=.coveragerc \
                   --mpl --mpl-results-path=pytest_images
      - coveralls/upload:
          parallel: true  # Indicate that this is a parallel build

  coveralls-finish:
    docker:
      - image: cimg/python:3.9
    steps:
      - coveralls/wait  # Notify Coveralls that the build is finished

workflows:
  sample:
    jobs:
      - build-and-test
      - coveralls-finish:
          requires:
            - build-and-test
