version: 2.1

orbs:
  python: circleci/python@1.2
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: additional pip install
          command: |
            pip install pytest pytest-mpl coverage pytest-cov coveralls
      - run:
          name: doc install
          command: |
            pip install mkdocs-awesome-pages-plugin pheasant mkdocstrings mkdocs-material
      - run:
          name: install netplotbrain
          command: |
            pip install ./
      - run:
          name: Run tests
          command: |
            coverage run --source=netplotbrain -m pytest --mpl
      - run:
          name: Save Coverage Data
          command: |
            if [ -f .coverage ]; then
              mkdir -p coverage_data
              cp .coverage coverage_data/.coverage.serial
            else
              echo "No coverage data file found."
            fi
      - run:
          name: Show Coverage Data File
          command: |
            ls -lh coverage_data
            coverage report --data-file=coverage_data/.coverage.serial
      - store_artifacts:
          path: pytest_images/
          destination: pytest_images
      - run:
          name: Coveralls
          command: coveralls

workflows:
  sample:
    jobs:
      - build-and-test
