# .circleci/config.yml

version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: |
            pip install pytest pytest-mpl coverage pytest-cov coveralls \
                        mkdocs-awesome-pages-plugin pheasant mkdocstrings mkdocs-material
      - run:
          name: Install netplotbrain
          command: pip install ./
      - run:
          name: List Installed Packages
          command: pip list
      - run:
          name: Run Tests with Coverage
          command: |
            pytest -v $(circleci tests glob "tests/**/*.py" | circleci tests split --split-by=timings) \
                   --cov=netplotbrain --cov-config=.coveragerc \
                   --mpl --mpl-results-path=pytest_images
      - run:
          name: Coverage Debugging Information
          command: |
            coverage debug sys --data-file=.coverage
            coverage debug data --data-file=.coverage
      - run:
          name: Save Coverage Data
          command: |
            if [ -f .coverage ]; then
              mkdir -p coverage_data
              cp .coverage coverage_data/.coverage.$CIRCLE_NODE_INDEX
            else
              echo "No coverage data file found."
            fi
      - run:
          name: Show Coverage Data File
          command: |
            ls -lh coverage_data
            coverage report --rcfile=.coveragerc --data-file=coverage_data/.coverage.$CIRCLE_NODE_INDEX
      - store_artifacts:
          path: pytest_images/
          destination: pytest_images
      - persist_to_workspace:
          root: .
          paths:
            - coverage_data

  coveralls-submit:
    docker:
      - image: cimg/python:3.9
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Coveralls and Coverage
          command: |
            pip install --upgrade coveralls coverage
      - run:
          name: Install netplotbrain
          command: pip install ./
      - run:
          name: List Coverage Data Files
          command: |
            ls -lh coverage_data
      - run:
          name: Combine Coverage Data
          command: |
            coverage combine --keep coverage_data
      - run:
          name: Show Combined Coverage Report
          command: |
            coverage report
      - run:
          name: Submit to Coveralls
          command: |
            coveralls --service=circle-ci --job_id=$CIRCLE_WORKFLOW_WORKSPACE_ID

workflows:
  build-and-submit:
    jobs:
      - build-and-test
      - coveralls-submit:
          requires:
            - build-and-test
